// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svuawbhoffnezqtnikdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2dWF3YmhvZmZuZXpxdG5pa2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTAzNTMsImV4cCI6MjA2OTg4NjM1M30.kVdsIqxU11tiYqiPc--ui_wWSTMJv718FIc9iiJVyRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});